package db.system;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mahesh
 */

import static db.system.DataBaseFunctions.createTable;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class CreateTable extends javax.swing.JFrame implements ActionListener{

    public String createQuery = "";
    
    JTable jTable1;
    JTextField jTextField1,jTextField2,jTextField3;
    JLabel jLabel1;
    String[] numbers= {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30",};
    String[] values = { "Char","Varchar","Varchar2","Number","Date" };
    JComboBox jComboBox1 = new JComboBox(values);
    JComboBox jComboBox2 = new JComboBox(numbers);
    JCheckBox jCheckBox1 = new JCheckBox();
    JCheckBox jCheckBox2 = new JCheckBox();
    JButton submit,cancel;
    DefaultTableModel model;
    /**
     * Creates new form CreateTable
     */
    public CreateTable() {
       
        jLabel1 = new JLabel("Enter Table Name");
        jTextField1 = new JTextField(30);
        jTextField2 = new JTextField(30);
        jTextField3 = new JTextField(30);
        submit = new JButton("Create Table");
        cancel = new JButton("Cancel");
        
        model = new DefaultTableModel();
        jTable1 = new JTable(model);
        jTable1.setRowHeight(30);
        model.addColumn("Column Name");
        model.addColumn("Data Type");
        model.addColumn("Length");
        model.addColumn("Primary Key");
        model.addColumn("Not Null");

        
        jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jTextField2));
        jTable1.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jComboBox1));
        jTable1.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jTextField3));

        jTable1.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(jCheckBox1));//primary key
        jTable1.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(jCheckBox2));//not null
    
        jTable1.setPreferredScrollableViewportSize(new Dimension(500,100));
        jTable1.setFillsViewportHeight(true);
        
        JScrollPane sp = new JScrollPane();
        sp.setViewportView(jTable1);
        
        setLayout(null);
        setTitle("CreateTable");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        submit.addActionListener(this);
        jTable1.addMouseListener(new MouseAdapter(){
           @Override
           public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    if(!jTextField2.getText().isEmpty()){
                        model.addRow(new Object[]{null,null,null,null,null,null}); 
                        getColumn();
                    }
                }
            }    
        });
     
        cancel.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 1){
                    createQuery = "";
                    model.setRowCount(0);
                    jTextField1.setText("");
                    model.addRow(new Object[]{null,null,null,null,null,null}); 
                    dispose();
                }
            }
        });
        
        jLabel1.setBounds(30,10,120,40);//add lable to continer
        jTextField1.setBounds(150, 10, 200, 40);
        sp.setBounds(30,70,520,400);
        submit.setBounds(130,480,150,40);
        cancel.setBounds(290,480,150,40);
        model.addRow(new Object[]{null,null,null, null, null, null});
        
        
        add(jLabel1);
        add(jTextField1);
        add(sp);
        add(submit);
        add(cancel);
        setPreferredSize(new Dimension(600,600));
        pack();
        //setSize(1400,800);
        setLocationRelativeTo(null);
        //setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void getTableName(){
        String table_name="student";
        createQuery="create table ";
        createQuery += table_name;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getColumn(){
        String name="";
        String data;
        data = "";
        
        name=jTextField2.getText();
        if(!jComboBox1.getSelectedItem().toString().isEmpty())
            data=jComboBox1.getSelectedItem().toString();
        String length="";
        length=jTextField3.getText();
        String datatype="("+length+")";
        
        boolean PK=jCheckBox1.isSelected();
        boolean NN=jCheckBox2.isSelected();
        
        createQuery+=name;
        if(data.equalsIgnoreCase("Date")){
            createQuery+=" "+data;
        }else{
            createQuery+=" "+data+datatype;
        }
        if(PK)
            createQuery+=" Primary Key";
        
        if(NN)
            createQuery+=" Not Null";
        
        jTextField2.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField3.setText("");
        jCheckBox2.setSelected(false);
        jCheckBox1.setSelected(false);
       
        createQuery+=",";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run(){
                CreateTable ct = new CreateTable();
                ct.setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(!jTextField2.getText().isEmpty())
            getColumn();
        System.out.println(createQuery);
        if(!createQuery.isEmpty()){
            createTable(createQuery,jTextField1.getText());
            model.setRowCount(0);
            jTextField1.setText("");
            model.addRow(new Object[]{null,null,null,null,null,null}); 
            createQuery = "";
        }else{
            JOptionPane.showMessageDialog(null, "Please Enter Infrormation !!!");
        }
    }
}
