/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.system;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Mahesh
 */
public class updateRowData extends javax.swing.JFrame {

    /**
     * Creates new form updateRowData
     */
    //JTable jTable1;
    JButton submit , cancel;
    int size;
    //DefaultTableModel model;
    JTextField [] jTextField=null;
    JLabel[] jLabel1=null;
    String[] columnNames ={};
    String[] values = {};
    String tableName = "";
    String [] str = {};
    String []newValues = {};
    
    public updateRowData(String tableName,String columnNames[],String[] values){
       /* tableName = tableName;
        columnNames = columnNames;
        values = values;*/
        size = columnNames.length;
        str = new String[size];
        jTextField = new JTextField[size];
        jLabel1 = new JLabel[size];
        submit = new JButton("Update");
        cancel = new JButton("Cancel");
        
        for(int i=0,y=50;i<size;i++){
            jLabel1[i] = new JLabel();
            jLabel1[i].setText(columnNames[i]);
            jLabel1[i].setBounds(30, y, 80, 40);
            add(jLabel1[i]);
            y+=50;
        }
        
        for(int i=0,y=50;i<size;i++){
            jTextField[i] = new JTextField(30);
            jTextField[i].setText(values[i]);
            jTextField[i].setBounds(110, y, 150, 40);
            add(jTextField[i]);
            y+=50;
        }
        
        setLayout(null);
        setTitle("View Rows");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for(int i=0;i<size;i++){
                    str[i] = jTextField[i].getText();
                }
                DataBaseFunctions.updateRow(tableName,columnNames,values,str,size);
                for(int i=0;i<size;i++){
                    jTextField[i].setText("");
                }
            }
        });
        
        cancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for(int i=0;i<size;i++){
                    jTextField[i].setText("");
                }
                dispose();
            }
        });
        
        submit.setBounds(130,480,150,40);
        cancel.setBounds(290,480,150,40);
        
        //add(sp);
        add(submit);
        add(cancel);
       
        setPreferredSize(new Dimension(600,600));
        pack();
        //setSize(1400,800);
        setLocationRelativeTo(null);
    }

    private updateRowData() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateRowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateRowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateRowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateRowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new updateRowData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
